[project]
name = "mycheckers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "libcomponent>=0.0.5",
    "pygame>=2.6.1",
    "trio>=0.32.0",
]
